image: ubuntu:20.04

build:
  stage: build
  script:
    - apt update
    - apt install android-tools-mkbootimg bc zip unzip bison build-essential curl clang tmate ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - git clone https://github.com/dylanaraps/neofetch
    - cd neofetch && make install
    - neofetch
    - sudo apt install tmate
    - wget https://raw.githubusercontent.com/yash3056/ci-tmate/main/tmate && sudo bash tmate


